# Generated by Django 2.2.7 on 2019-12-03 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmsite', '0006_auto_20191202_1530'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productID', models.ManyToManyField(blank=True, to='farmsite.Product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wishlists',
                'verbose_name_plural': 'Wishlists',
            },
        ),
    ]
