# Generated by Django 2.2.6 on 2019-11-13 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productType', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Product Photo')),
                ('weight', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('available', models.BooleanField()),
                ('discount', models.IntegerField()),
                ('discription', models.TextField()),
                ('prime', models.BooleanField()),
                ('productType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmsite.ProductType')),
            ],
        ),
    ]
