# Generated by Django 2.2.7 on 2019-12-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='couponCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('validity', models.DateTimeField()),
                ('limit', models.IntegerField()),
                ('products', models.ManyToManyField(to='farmsite.Product')),
            ],
            options={
                'verbose_name': 'Coupon Codes',
                'verbose_name_plural': 'Coupon Code',
            },
        ),
    ]
