# Generated by Django 2.2.7 on 2019-12-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsite', '0004_address_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Testimonial')),
                ('name', models.TextField(max_length=100)),
                ('text', models.TextField(max_length=500)),
                ('designation', models.TextField(max_length=100)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonial',
            },
        ),
    ]
