# Generated by Django 2.2.7 on 2019-12-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsite', '0006_auto_20191202_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nutFacts',
            field=models.TextField(default='Hello'),
            preserve_default=False,
        ),
    ]
