# Generated by Django 2.2.7 on 2019-12-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsite', '0007_product_nutfacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activate'),
            preserve_default=False,
        ),
    ]
