# Generated by Django 2.2.7 on 2019-12-07 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmsite', '0008_couponcode_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponcode',
            name='validity',
        ),
    ]
